export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
      <header className="container mx-auto px-4 py-6">
        <nav className="flex justify-between items-center">
          <div className="text-2xl font-bold text-blue-600">
            AI Resume Builder
          </div>
          <div className="space-x-4">
            <button className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700">
              Get Started
            </button>
          </div>
        </nav>
      </header>

      <main className="container mx-auto px-4 py-20">
        <div className="text-center max-w-4xl mx-auto">
          <h1 className="text-5xl font-bold text-gray-900 mb-6">
            Create professional resumes with AI assistance
          </h1>
          <p className="text-xl text-gray-600 mb-8">
            Built with modern technology for maximum efficiency
          </p>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mt-20">
            
            <div className="text-center p-6 bg-white rounded-lg shadow-sm border hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-blue-100 rounded-lg mx-auto mb-4 flex items-center justify-center">
                <span className="text-blue-600 font-bold">✓</span>
              </div>
              <h3 className="font-semibold text-lg mb-2">AI writing</h3>
              <p className="text-gray-600">AI writing functionality ready to use</p>
            </div>
            
            <div className="text-center p-6 bg-white rounded-lg shadow-sm border hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-blue-100 rounded-lg mx-auto mb-4 flex items-center justify-center">
                <span className="text-blue-600 font-bold">✓</span>
              </div>
              <h3 className="font-semibold text-lg mb-2">Templates</h3>
              <p className="text-gray-600">Templates functionality ready to use</p>
            </div>
            
            <div className="text-center p-6 bg-white rounded-lg shadow-sm border hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-blue-100 rounded-lg mx-auto mb-4 flex items-center justify-center">
                <span className="text-blue-600 font-bold">✓</span>
              </div>
              <h3 className="font-semibold text-lg mb-2">PDF export</h3>
              <p className="text-gray-600">PDF export functionality ready to use</p>
            </div>
            
            <div className="text-center p-6 bg-white rounded-lg shadow-sm border hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-blue-100 rounded-lg mx-auto mb-4 flex items-center justify-center">
                <span className="text-blue-600 font-bold">✓</span>
              </div>
              <h3 className="font-semibold text-lg mb-2">ATS optimization</h3>
              <p className="text-gray-600">ATS optimization functionality ready to use</p>
            </div>
            
          </div>

          <div className="mt-16 p-8 bg-gray-50 rounded-lg">
            <h2 className="text-2xl font-bold mb-4">Ready to Launch! 🚀</h2>
            <p className="text-gray-600 mb-6">Your AI Resume Builder clone is ready for customization</p>
            <div className="flex justify-center gap-4">
              <button className="bg-green-600 text-white px-6 py-3 rounded-md hover:bg-green-700">
                Start Building
              </button>
              <button className="bg-gray-200 text-gray-800 px-6 py-3 rounded-md hover:bg-gray-300">
                View Documentation
              </button>
            </div>
          </div>
        </div>
      </main>

      <footer className="bg-gray-900 text-white py-12 mt-20">
        <div className="container mx-auto px-4 text-center">
          <p>© 2026 AI Resume Builder Clone. Built with #dayXofkillingSaaS</p>
          <p className="text-gray-400 mt-2">Generated by SaaS Automation System</p>
        </div>
      </footer>
    </div>
  )
}